### ISSUE TITLE
Need help configuring forked repo for future pull requests

### ISSUE THREAD

**Issue by chicago-joe** [jamesmawm/High-Frequency-Trading-Model-with-IB#12]
Hi @jamesmawm ,

I'm trying to properly set up my forked repo so that I can pull your commits and branch trees into my fork on a regular basis.  How should I do this? 

I think I need to set your repo as a remote branch, but I'm not sure how to configure tracking, set-upstream, and other settings necessary to do this correctly. 

Also, if I merge one of your branches with mine, will the commit log retain both of our histories?

Thanks for the help!

**Comment by jamesmawm** [comment]
Try using Sourcetree, it has a very user-friendly UI for doing all things
git.

You can setup two remotes. In your local branch you can set a remote
branch, such as mine, to track from.

Yes, commit logs will be retained. But you can choose to squash commits or
rebase.

I'm using Sourcetree too to help me do all these in a few simple clicks.

**Comment by chicago-joe** [comment]
Finally got it all set up - thanks for the help! 
Looks like I won't be using Git Bash anymore 😄
