### ISSUE TITLE
Is this program supposed to be profitable?

### ISSUE THREAD

**Issue by YONATAN10111** [jamesmawm/High-Frequency-Trading-Model-with-IB#17]
I am running the program with stocks on paper trade. The code is losing money. Does the order of the 2 stocks I use matter? And how much time does it usually takes until I see even a plus in the profit?

Thank you

**Comment by jamesmawm** [comment]
This project is meant for research, and entirely up to you to setup your own trading infrastructure or strategies. Profitable trades depends on your risk appetite, how well you know the market you're trading, market timing, signal generation methodology, and among many other factors.

**Comment by YONATAN10111** [comment]
Thank you very much :)
