### ISSUE TITLE
Tried to run Main.py & ended with error

### ISSUE THREAD

**Issue by Prchakr** [jamesmawm/High-Frequency-Trading-Model-with-IB#4]
Please help on this.
Tried to run Main.py & ended with error

 from models.hft_model import HFTModel

  File "C:\Users\Raji\Downloads\High-Frequency-Trading-Model-with-IB-master\models\hft_model.py", line 378
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by jamesmawm** [comment]
This code is in python 2 syntax. Are you running on python 3?
